# 按固定清单准备离线 OCR 模型，缓存与源码分离，运行时不下载。
include("${CMAKE_CURRENT_LIST_DIR}/OpenSTModelCache.cmake")
file(READ "${PROJECT_SOURCE_DIR}/packaging/ocr/models.json" OPEN_ST_OCR_MANIFEST)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/packaging/ocr/models.json")
string(JSON OPEN_ST_MODEL_COUNT LENGTH "${OPEN_ST_OCR_MANIFEST}" models)
if(NOT OPEN_ST_MODEL_COUNT EQUAL 6)
    message(FATAL_ERROR "OCR 清单必须包含 fast/best 中英日六份模型")
endif()
set(OPEN_ST_OCR_MODEL_CACHE "${PROJECT_SOURCE_DIR}/.cache/ocr-models")
foreach(OPEN_ST_MODEL_INDEX RANGE 0 5)
    foreach(OPEN_ST_FIELD family language url sha256 size)
        string(JSON OPEN_ST_MODEL_${OPEN_ST_FIELD} GET "${OPEN_ST_OCR_MANIFEST}" models ${OPEN_ST_MODEL_INDEX} ${OPEN_ST_FIELD})
    endforeach()
    if(NOT OPEN_ST_MODEL_family MATCHES "^(fast|best)$" OR NOT OPEN_ST_MODEL_language MATCHES "^(chi_sim|eng|jpn)$")
        message(FATAL_ERROR "OCR 模型标识无效")
    endif()
    set(OPEN_ST_MODEL_PATH "${OPEN_ST_OCR_MODEL_CACHE}/${OPEN_ST_MODEL_family}/${OPEN_ST_MODEL_language}.traineddata")
    open_st_cached_model_file("${OPEN_ST_MODEL_PATH}" "${OPEN_ST_MODEL_url}"
        "${OPEN_ST_MODEL_sha256}" "${OPEN_ST_MODEL_size}")
endforeach()
