# 按固定清单准备离线 OCR 模型，缓存与源码分离，运行时不下载。
file(READ "${PROJECT_SOURCE_DIR}/packaging/ocr/models.json" OPEN_ST_OCR_MANIFEST)
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${PROJECT_SOURCE_DIR}/packaging/ocr/models.json")
string(JSON OPEN_ST_MODEL_COUNT LENGTH "${OPEN_ST_OCR_MANIFEST}" models)
if(NOT OPEN_ST_MODEL_COUNT EQUAL 6)
    message(FATAL_ERROR "OCR 清单必须包含 fast/best 中英日六份模型")
endif()
set(OPEN_ST_OCR_MODEL_CACHE "${PROJECT_SOURCE_DIR}/.cache/ocr-models")
foreach(OPEN_ST_MODEL_INDEX RANGE 0 5)
    foreach(OPEN_ST_FIELD family language url sha256 size)
        string(JSON OPEN_ST_MODEL_${OPEN_ST_FIELD} GET "${OPEN_ST_OCR_MANIFEST}" models ${OPEN_ST_MODEL_INDEX} ${OPEN_ST_FIELD})
    endforeach()
    if(NOT OPEN_ST_MODEL_family MATCHES "^(fast|best)$" OR NOT OPEN_ST_MODEL_language MATCHES "^(chi_sim|eng|jpn)$")
        message(FATAL_ERROR "OCR 模型标识无效")
    endif()
    set(OPEN_ST_MODEL_PATH "${OPEN_ST_OCR_MODEL_CACHE}/${OPEN_ST_MODEL_family}/${OPEN_ST_MODEL_language}.traineddata")
    set(OPEN_ST_MODEL_VALID FALSE)
    if(EXISTS "${OPEN_ST_MODEL_PATH}")
        file(SHA256 "${OPEN_ST_MODEL_PATH}" OPEN_ST_MODEL_ACTUAL)
        if(OPEN_ST_MODEL_ACTUAL STREQUAL OPEN_ST_MODEL_sha256)
            set(OPEN_ST_MODEL_VALID TRUE)
        endif()
    endif()
    if(NOT OPEN_ST_MODEL_VALID)
        file(MAKE_DIRECTORY "${OPEN_ST_OCR_MODEL_CACHE}/${OPEN_ST_MODEL_family}")
        file(DOWNLOAD "${OPEN_ST_MODEL_url}" "${OPEN_ST_MODEL_PATH}.part"
            EXPECTED_HASH "SHA256=${OPEN_ST_MODEL_sha256}" TLS_VERIFY ON TIMEOUT 180 STATUS OPEN_ST_MODEL_STATUS)
        list(GET OPEN_ST_MODEL_STATUS 0 OPEN_ST_MODEL_CODE)
        if(NOT OPEN_ST_MODEL_CODE EQUAL 0)
            message(FATAL_ERROR "OCR 模型下载或验证失败：${OPEN_ST_MODEL_STATUS}")
        endif()
        file(RENAME "${OPEN_ST_MODEL_PATH}.part" "${OPEN_ST_MODEL_PATH}")
    endif()
    file(SIZE "${OPEN_ST_MODEL_PATH}" OPEN_ST_MODEL_SIZE)
    if(NOT OPEN_ST_MODEL_SIZE EQUAL OPEN_ST_MODEL_size)
        message(FATAL_ERROR "OCR 模型长度不符：${OPEN_ST_MODEL_PATH}")
    endif()
endforeach()
